username='Gnana'
password='Asdfg1234'
account='bf76137.us-east-2.aws'
warehouse='COMPUTE_WH'
database='STOCK_DATA'
role='SYSADMIN'
schema='PUBLIC'
stage_table='STOCKDATA'
table='STOCKS'

# username='SRUSHTI104'
# password='Enamored104@'
# account='ypa65958.us-east-1'
# warehouse='COMPUTE_WH'
# database='STOCK'
# role='SYSADMIN'
# schema='PUBLIC'
# stage_table='STOCKS'
# table='STOCK_TBL'
# stored_procedure='fetch_Stocks'

