create or replace TABLE STORM_FATALITIES (
    FAT_YEARMONTH NUMBER(38,0),
    FAT_DAY NUMBER(38,0),
    FAT_TIME NUMBER(38,0),
    FATALITY_ID NUMBER(38,0),
    EVENT_ID NUMBER(38,0),
    FATALITY_TYPE VARCHAR(10),
    FATALITY_DATE TIMESTAMP_NTZ(9),
    FATALITY_AGE NUMBER(38,0),
    FATALITY_SEX VARCHAR(10),
    FATALITY_LOCATION VARCHAR(16777216),
    EVENT_YEARMONTH NUMBER(38,0)
);